aplicacao/DiretorioJornalistas/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

from autenticacao import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autenticacao.urls')),
    path('historico', include('historico.urls')),
    path('obras', include('obras.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

aplicacao/autenticacao/urls.py
from django.urls import path, re_path

from .views import *


urlpatterns = [
    path('', home_view), #Busca de joranlistas e Glossario
    path('',  lista_jornalistas_view, name='jornalistas'),

    path('jornalista', dados_jornalista_view, name="dados-jornalista"),
    path('jornalista/cadastro', cadastro_jornalista_view, name="cadastro-jornalista"),
    path('jornalista/dados-jornalista',dados_jornalista_view, name="dados-jornalista"),
    path('jornalista/edita-jornalista',edita_jornalista_view, name="edita-jornalista"),


    path('revisor/<int:id>', lista_jornalistas_associados_view, name="jornalista-associados"),
    path('revisor/<int:id>/valida/<int:id_jornalista>', valida_jornalista_view, name="valida-jornalista"),


    path("login", login_view, name='login'),
    path("register", register_view, name='register'), 
    path("logout", logout_view, name='logout' ),
]

aplicacao/obras/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path("cadastro", cadastro_obra, name="cadastro_obra"),
    path("edita", cadastro_obra, name="edita_obra"),
    path("lista", cadastro_obra, name="lista_obra"),
]

aplicacao/autenticacao/models/associacao.py
from django.db import models
from opcoes.models.redesSociais import RedesSociais

class Associacao(models.Model):
    nome_fantasia = models.CharField(max_length=254)
    razao_social = models.CharField(max_length=254)
    cnpj = models.IntegerField()
    ddd_telefone = models.CharField(max_length=2)
    telefone = models.CharField(max_length=9)
    email = models.EmailField(max_length=254)
    presidente = models.CharField(max_length=254)
    # rede_sociais = models.ForeignKey(RedesSociais, on_delete=models.DO_NOTHING)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}'.format(self.nome_fantasia)

aplicacao/autenticacao/models/jornalista.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
    

from autenticacao.models import Revisor, Associacao
from opcoes.models import RedesSociais, Cidades, Estados, Genero, EstadoCivil
from obras.models import ObraJornalistica
from historico.models import HistoricoProfissional


class Jornalista(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    associacao = models.ForeignKey(Associacao,on_delete=models.DO_NOTHING)
    nome_de_guerra = models.CharField(max_length=50)
    cpf = models.CharField(max_length=11)
    data_de_nascimento = models.DateField(null=True, blank = True)
    telefone = models.CharField( max_length=11,null=True, blank = True)
    estado = models.ForeignKey(Estados, on_delete=models.DO_NOTHING,null=True, blank = True)
    cidade = models.ForeignKey(Cidades, on_delete=models.DO_NOTHING,null=True, blank = True)
    genero = models.ForeignKey(Genero, on_delete=models.DO_NOTHING, null=True, blank = True)
    estado_civil = models.ForeignKey(EstadoCivil, on_delete=models.DO_NOTHING,null=True, blank = True)
    foto = models.ImageField(null=True, blank = True)
    registro = models.CharField( max_length=50,null=True, blank = True)
    # diploma = models.ImageField( upload_to=None, height_field=None, width_field=None, max_length=None)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)
    aprovado = models.BooleanField(default=False)
    # revisor_responsavel = models.ForeignKey(Revisor,on_delete=models.DO_NOTHING)
    # obras_jornalisticas = models.ManyToManyField(ObraJornalistica)
    # historico_profissional = models.ManyToManyField(HistoricoProfissional)

    def __str__(self):
        return '{}'.format(self.nome_de_guerra)

        
    
    

aplicacao/autenticacao/forms/authForm.py
from django import forms

class LoginForm(forms.Form):
    #email = forms.CharField(required=True, widget=forms.TextInput(attrs={'id':'caixa-login','class': 'login', 'placeholder':'login'}))
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={'id':'caixa-login','class': 'form-control', 'placeholder':'Usuário'}))
    password = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Senha'}), required=True)
        
class RegisterForm(forms.Form):
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Usuário'}))
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder':'Email'}))
    password = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Senha'}), required=True)

aplicacao/autenticacao/forms/jornalistaForm.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from autenticacao.models import Jornalista
from autenticacao.models import Associacao

class JornalistaForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(JornalistaForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Jornalista
        fields = [
            'usuario',
            'associacao',
            'nome_de_guerra',
            'cpf',
            'telefone',
            'data_de_nascimento',
            'genero',
            'estado_civil',
        ]

        widgets = {
            'usuario': forms.HiddenInput(),
            'associacao': forms.Select(attrs={'class': 'form-control2'}),
            'nome_de_guerra' : forms.TextInput(attrs={'class': 'form-control2', 'placeholder':'Nome de Gerra'}),
            'cpf': forms.TextInput(attrs={'class': 'form-control2', 'placeholder':'CPF','required':'True'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control2', 'placeholder':'Telefone'}),
            'data_de_nascimento': forms.DateInput(attrs={'class': 'form-control2', 'placeholder':'Data de nascimento'}),
            'genero': forms.Select(attrs={'class': 'form-control2'}),
            'estado_civil': forms.Select(attrs={'class': 'form-control2'}),
        }

aplicacao/autenticacao/views/authViews.py
from django.http import request
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.models import User
from django.conf import settings

from autenticacao.forms.authForm import LoginForm, RegisterForm

def login_view(request):
    loginForm = LoginForm()
    message = None

    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        loginForm = LoginForm(request.POST)

        if loginForm.is_valid():
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                _next = request.GET.get('next')
                if _next is not None:
                    return redirect(_next)
                else:
                    return redirect('/')
            else:
                message = {
                    'type':'danger',
                    'text':'Dados de usuário incorretos'
                }

    context = {
        'form': loginForm,
        'message': message,
        'title': 'Login',
        'button_text': 'Entrar',
        'link_text': 'Registre agora',
        'link_href': '/register'
    }

    return render(request, template_name='login.html', context=context, status=200)

def register_view(request):
    registerForm = RegisterForm()
    message = None

    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        registerForm = RegisterForm(request.POST)

        if registerForm.is_valid():
            verifyUsername = User.objects.filter(username=username).first()
            verifyEmail = User.objects.filter(email=email).first()

            if verifyUsername is not None:
                message = {'type': 'danger', 'text': 'Já existe um usuário com este username!'}
            elif verifyEmail is not None:
                message = {'type': 'danger', 'text': 'Já existe um usuário com este email!'}
            else:
                user = User.objects.create_user(username, email, password)
                if user is not None:
                    message = {'type': 'success', 'text': 'Conta criada com sucesso!' }
                    login(request, user)
                    return redirect('/jornalista/cadastro')            

                else:
                    message = {'type':'danger', 'text': 'Um erro ocorreu ao tentar criar o usuário.'}

        
    
    context = {
        'form': registerForm,
        'message': message,
        'title': 'Registrar',
        'button_text': 'Registrar',
        'link_text': 'Login',
        'link_href':'/login'
    }

    return render(request, template_name='login.html', context=context, status=200)

def logout_view(request):
    logout(request)
    return redirect('/login')

aplicacao/autenticacao/views/homeViews.py
from django.shortcuts import render
from django.core import paginator
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import HttpResponse

from ..models import Jornalista

def home_view(request):
    context = {}
    jornalistas = Jornalista.objects.all()

    if (request.GET.get('inicial') != None):            # Verifica se a pesquisa foi pelo glossario
        filtro = []
        for i in jornalistas:                           
            if (str(i)).upper()[0] == request.GET.get('inicial'): # Lista os Jornalistas com a inicial escolhida.
                filtro.append(i)

        context = {
            'form': filtro                              # Envia para Form os jornalistas encontrados.
        }

    if request.GET.get('name') != None:                 # Verifica se a pesquisa foi pelo nome.
        name = request.GET.get('name')
        jornalistas = jornalistas.filter(nome_de_guerra__contains=name)     # Filta os jornalistas pelo nome.

        context = {
            'form': jornalistas                         # Envia para Form os jornalistas encontrados.
        }

    return render(request, template_name='index.html', context=context, status=200)


def lista_jornalistas_view(request):
    name = request.GET.get('name')
    # cidade = request.GET.get('cidade')
    # estado = request.GET.get('estado')

    jornalistas = Usuario.object
    if name is not None and name != '':
        jornalistas = jornalistas.filter(Q(user__first_name__contains=name) | Q(user__username__contains=name))
    # else : 
    #     if cidade is not None:
    #         jornalistas = jornalistas.filter(cidade__id=cidade)
    #     elif estado is not None:
    #         jornalistas = jornalistas.filter(cidade__estado=estado)
    if len(jornalistas) > 0:
        paginator = Paginator(jornalistas, 8)
        page = request.GET.get('page')
        jornalistas = paginator.get_page(page)
    
    get_copy = request.GET.copy()
    parameters = get_copy.pop('page', True) and get_copy.urlencode()

    context = {
        'jornalistas': jornalistas,
        'parameters': parameters
    }
    
    return render(request, template_name='jornalistas.html', context=context, status=200)

aplicacao/autenticacao/views/jornalistasViews.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect, get_list_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from autenticacao.forms.jornalistaForm import JornalistaForm
from opcoes.forms.redesForm import RedesForm
from autenticacao.models import Jornalista, Associacao
from opcoes.models import Genero, EstadoCivil, RedesSociais, TipoDeRedeSocial


@login_required
def cadastro_jornalista_view(request):

    initial = {'usuario':request.user}
    message = None

    if request.method == 'POST':
        jornalistaForm = JornalistaForm(request.POST, initial=initial)
        try: 
          dados_form = jornalistaForm.data

          jornalista = Jornalista()

          jornalista.usuario=request.user
          jornalista.associacao_id=dados_form['associacao']
          jornalista.nome_de_guerra=dados_form['nome_de_guerra']
          jornalista.cpf=dados_form['cpf']
          jornalista.telefone=dados_form['telefone']
          jornalista.data_de_nascimento=dados_form['data_de_nascimento']
          jornalista.genero_id=dados_form['genero']
          jornalista.estado_civil_id=dados_form['estado_civil']

          jornalista.save()

          message = {'type': 'sucess', 'text': 'Dados atualizados com sucesso'}
          return redirect('/jornalista/dados-jornalista')   
        except Exception as e:
          message = { 'type': 'danger', 'text': 'Erro ao salvar jornalista. Descrição: %s' %e }

    else:
        jornalistaForm = JornalistaForm(initial=initial)


    context = {
        'form': jornalistaForm,
        'message': message
    }

    return render(request, template_name='jornalista/cadastro-jornalista.html', context=context, status=200)


@login_required
def dados_jornalista_view(request):
  jornalista = get_object_or_404(Jornalista, usuario=request.user)
  redesForm = RedesForm()
  print(jornalista)
  if request.method == 'POST':
    redesForm = RedesForm(request.POST)
    dados_form = redesForm.data
    
    if dados_form['telegram']:
      telegram = RedesSociais(
        tipo_de_rede_social=TipoDeRedeSocial.objects.get(id=1),
        link = dados_form['telegram']
      )
      telegram.save()
    try: 
      telegram = RedesSociais( )
      telegram.jornalista = jornalista

      telegram.link = dados_form['telegram']
      telegram.save()
      print(telegram.link)
          # if redes_form['facebook'] != "":
          #   facebook = RedesSociais( )
          #   facebook.jornalista = jornalista
          #   facebook.tipo_de_rede_social = 2
          #   facebook.link = redes_form['facebook']
          #   facebook.save()

          # if redes_form['podcast'] != "":
          #   podcast = RedesSociais( )
          #   podcast.jornalista = jornalista
          #   podcast.tipo_de_rede_social = 3
          #   podcast.link = redes_form['podcast']
          #   podcast.save()

          # if redes_form['linkedin'] != "":
          #   linkedin = RedesSociais( )
          #   linkedin.jornalista = jornalista
          #   linkedin.tipo_de_rede_social = 4
          #   linkedin.link = redes_form['linkedin']
          #   linkedin.save()

          # if redes_form['twitter'] != "":
          #   twitter = RedesSociais( )
          #   twitter.jornalista = jornalista
          #   twitter.tipo_de_rede_social = 5
          #   twitter.link = redes_form['twitter']
          #   twitter.save()

          # if redes_form['site'] != "":
          #   site = RedesSociais( )
          #   site.jornalista = jornalista
          #   site.tipo_de_rede_social = 6
          #   site.link = redes_form['site']
          #   site.save()

      message = {'type': 'sucess', 'text': 'Dados atualizados com sucesso'}
      return redirect('/') 

    except Exception as e:
      message = { 'type': 'danger', 'text': 'Erro ao salvar jornalista. Descrição: %s' %e }

  else:
    redesForm = redesForm()


  context = {
    'redes': redesForm
  }
  return render(request, template_name='jornalista/dados-jornalista.html', context=context, status=200)

@login_required
def edita_jornalista_view(request):
  jornalista = get_object_or_404(Jornalista, usuario=request.user)
  if request.method == 'POST':
     jornalistaForm = JornalistaForm(request.POST, instance=jornalista)
     redesForm = RedesForm()
  else:
    jornalistaForm = JornalistaForm(instance=jornalista)
    redesForm = RedesForm() 

  # if jornalistaForm.is_valid():

  #   message = { 'type': 'sucess', 'text': 'Dados atualizados com sucesso'}
    
  #   return redirect('/')

  # else:
  #   message = { 'type': 'danger', 'text': 'Dados inválidos'}

  # context = {
  #   'form': jornalistaForm,
  #     # 'redes': redesForm,
  #   'id': id,
  # }

  # jornalista.save()

  # return redirect(home_view)
  context = {}
  return render(request, template_name='jornalista/edita-jornalista.html', context=context, status=200)

aplicacao/autenticacao/views/revisorViews.py
from django.shortcuts import render
from django.http import HttpResponse

def lista_jornalistas_associados_view(request):
  
  return HttpResponse("Você está listando jornalistas associados")

def valida_jornalista_view(request):
  return HttpResponse("Você está detalhado o jornalista para validar")

aplicacao/autenticacao/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet"> 
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
  
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/cadastro.css' %}">

</head>
<body>

  {% block content %}{% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

aplicacao/autenticacao/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<header>
  {% include 'partials/menu.html' %}
</header>

<main>
    <form action={% url 'jornalistas' %} method="GET" style="padding-top: 8vh;">
        <div class="textoApjor">
            <h1>Diretório Piloto de<br>Jornalistas no Brasil</h1>
            <h2>Busque um jornalista</h2>
        </div>

        <div class="texto-botoes">
            <input type="text" class="form-control" name="name" placeholder="Buscar por nome">

            <div class="col form-group mb-0">
                <button type="submit" class="btn btn-primary">Buscar</button>
            </div>
        </div>
    </form>

    <div class="alfabeto">
        <form action={% url 'jornalistas' %} method="GET" id="alfabeto">
            <button type="submit" name="inicial" value="A">A</button>
            <button type="submit" name="inicial" value="B">B</button>
            <button type="submit" name="inicial" value="C">C</button>
            <button type="submit" name="inicial" value="D">D</button>
            <button type="submit" name="inicial" value="E">E</button>
            <button type="submit" name="inicial" value="F">F</button>
            <button type="submit" name="inicial" value="G">G</button>
            <button type="submit" name="inicial" value="H">H</button>
            <button type="submit" name="inicial" value="I">I</button>
            <button type="submit" name="inicial" value="J">J</button>
            <button type="submit" name="inicial" value="K">K</button>
            <button type="submit" name="inicial" value="L">L</button>
            <button type="submit" name="inicial" value="M">M</button>
            <button type="submit" name="inicial" value="N">N</button>
            <button type="submit" name="inicial" value="O">O</button>
            <button type="submit" name="inicial" value="P">P</button>
            <button type="submit" name="inicial" value="Q">Q</button>
            <button type="submit" name="inicial" value="R">R</button>
            <button type="submit" name="inicial" value="S">S</button>
            <button type="submit" name="inicial" value="T">T</button>
            <button type="submit" name="inicial" value="U">U</button>
            <button type="submit" name="inicial" value="V">V</button>
            <button type="submit" name="inicial" value="W">W</button>
            <button type="submit" name="inicial" value="X">X</button>
            <button type="submit" name="inicial" value="Y">Y</button>
            <button type="submit" name="inicial" value="Z">Z</button>
        </form>
    </div>

    {% csrf_token %}
    {% if form %}
    <div class="jornaListas">
        {% for f in form %}
            <button style="border: none; display: flex; width: fit-content; background-color: transparent;">
                <div class="image-pessoa" style="border: none;">
                    <img
                        src="{% static 'img/perfil.png' %}"
                        width="130"
                        height="130"
                        alt=""
                    />
                </div>
                <div class="card">
                    <h5>{{ f.nome_de_guerra }}</h5>
                    <span><b >Associação:</b> {{ f.associacao }}</span>
                    <span><b>Localidade:</b> {{ f.get_cidade_display }}</span>
                    <span><b>Especialidade/Áreas de Atuação:</b> {{f.site}}</span>
                </div>
            </button>
            
        {% endfor %}
    </div>
    {% endif %}

</main>

<footer>
  {% include 'partials/footer.html' %}
</footer>

{% endblock content %}

aplicacao/autenticacao/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<header>
  {% include 'partials/menu.html' %}
</header>

<main>

<div>
  {% if message is not None %}
  <div class="alert alert-{{ message.type }}">{{ message.text }}</div>
{% endif %}
</div>

<div class="container-fluid">
  <div class="row">
    <div class ="col p-0">
      <div class ="position-relative figure"> 
        <div class ="filter-orange">  
          <img src="{% static 'img/jornalismo-1.png' %}" class="img-fluid p-0 imagem-login" alt="Imagem com maquina de escrever">
        </div>
        <div class="position-absolute top-50 start-0 translate-middle-y">
          <h1 class ="titulo-pag mx-2 text-center fw-bold">Diretório Piloto de Jornalistas no Brasil</h1>
        </div>
      </div>
    </div>
    <div class="col position-relative">
      <div class="row justify-content-center">
        <div class="col-6">
          <div class="">
            <div>
              <p class ="text-center mt-4">APJOR-Associação dos Jornalistas</p> 
            </div>
            <div class="position-absolute top-50 start-50 translate-middle">
              <form class="text-center" method="POST" action="">
                {% csrf_token %}
                <div class="small">
                  <p>Não é um membro? <a class="fw-bold link" href="{{link_href}}">{{link_text}}</a></p>
                </div>
                <div>
                  <div class="form-group row g-2 p-2 m-2">
                  
                    {{ form.username }}
                    {{ form.email }}
                    {{ form.password }}

                    {% for erro in f.errors %}
                      <div class="invalid-feedback" style="display: initial;">{{ error }}</div>
                    {% endfor %}
                      
                    <button type="submit" class = "btn btn-primary btn-block">Entrar</button>
                  </div>
                </div>      
                <div class="small">
                  <p class="">Esqueceu sua senha? <a class="fw-bold link" href="#">Clique aqui</a></p>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

  <footer>
    {% include 'partials/footer.html' %}
  </footer>
{% endblock content %}